-- PV统计数据库初始化脚本
-- 兼容原有pv.php的表结构

-- 详情表（记录每次请求）
CREATE TABLE IF NOT EXISTS DETAIL (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    IP TEXT NOT NULL,
    TIME INTEGER NOT NULL,
    REFERER TEXT,
    SERVER TEXT,
    TYPE TEXT,
    SINGID TEXT
);

-- 统计表（优化查询性能）
CREATE TABLE IF NOT EXISTS STATS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SERVER TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    SINGID TEXT NOT NULL,
    COUNT INTEGER DEFAULT 1,
    LAST_TIME INTEGER NOT NULL,
    UNIQUE(SERVER, TYPE, SINGID)
);

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_detail_time ON DETAIL(TIME);
CREATE INDEX IF NOT EXISTS idx_detail_server ON DETAIL(SERVER);
CREATE INDEX IF NOT EXISTS idx_detail_type ON DETAIL(TYPE);
CREATE INDEX IF NOT EXISTS idx_detail_singid ON DETAIL(SINGID);
CREATE INDEX IF NOT EXISTS idx_stats_singid ON STATS(SINGID);
